### PR TITLE
First implementation of the ArXiv API in add paper

### PR DESCRIPTION
**Pull request by josephabirached**

### CODE REVIEW

**Review by kerzol — CHANGES_REQUESTED** [review]
Hello,

1. When user provide an arxiv url, we cannot keep the whole paper. There maybe some licence issues with that. I suggest to remove the paper after taking the "screen-shot" of the first page, and use arxiv url as `getlink` in `papers` table. 
Maybe we can just move the arXiv link into `request.form['url']`, and the following code will apply 
https://github.com/kerzol/papers/blob/master/papersite/onepaper.py#L289

2. I don't see why the ArXiv URL input field and associated `Search article` button should be disabled after the first search. Can you explain your idea to me, please ?

**Comment by josephabirached** [comment]
Hello,
1. I modified the behavior of the API to delete the file after adding a new paper from Arxiv
2. I disabled the field to avoid that the user changes the URL of the Arxiv paper. If a user changes the URL it would result in another paper being added or a bad request if the URL is invalid.

**Comment by kerzol** [comment]
Hi Joseph, It is 90% good. 
Only some minor changes, that I describe below, and we will be ready to merge and deploy!

> 1. I modified the behavior of the API to delete the file after adding a new paper from Arxiv

Super !


> 2. I disabled the field to avoid that the user changes the URL of the Arxiv paper. If a user changes the URL it would result in another paper being added or a bad request if the URL is invalid.

I think that we should not disable the field or button [Search Article].
In this case particular case, it it better to trust user and give him more freedom.

I also found a regression: now it's not possible to add an article without specifying Arxiv URL.
Is it a bug or a feature ? : )

**Comment by josephabirached** [comment]
> I think that we should not disable the field or button [Search Article].
In this case particular case, it it better to trust user and give him more freedom.

Removed the lines of code that disabled the input

> I also found a regression: now it's not possible to add an article without specifying Arxiv URL.
Is it a bug or a feature ? : )

It was a bug. It is fixed now .

**Pull request merged**
